apiVersion: v1
kind: Service
metadata:
  name: ebpf-observer
  namespace: kube-system
  labels:
    app: ebpf-observer
spec:
  selector:
    app: ebpf-observer
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
