apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # All services use network_mode: host → Grafana reaches Prometheus on localhost
    url: http://localhost:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: "5s"
      httpMethod: POST
